### PR TITLE
Fixed tsc erros. As described in stackoverflow post.

### PR DESCRIPTION
**Pull request by Olian04**
Relevant stackoverflow post: https://stackoverflow.com/questions/70195412/how-do-i-compile-my-typescript-code-with-import-statements/70197398

Note: This PR is not tested with real credentials.

### CODE REVIEW

**Review by ProGamer2711 — CHANGES_REQUESTED** [review]
Still the same error. Error:
`import { Command } from "../../Interfaces";
^^^^^^

SyntaxError: Cannot use import statement outside a module`

**Review by ProGamer2711 — COMMENTED** [review]
I have a .gitignore file. I just added it itself to ignore. I'm gonna add it next commit.

**Review by ProGamer2711 — COMMENTED** [review]
If you have Discord you can add me. My tag is ProGamer2711#5385

**Comment by Olian04** [comment]
> Still the same error. Error: `import { Command } from "../../Interfaces"; ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module`

Delete `dist` folder. Then run `npm run dev`

**Comment by ProGamer2711** [comment]
Still getting the same error.

**Comment by Olian04** [comment]
> Still getting the same error.

Could you post the entire error?

**Comment by ProGamer2711** [comment]
> > Still getting the same error.
> 
> Could you post the entire error?

> C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Commands\Configurations\blacklistWords.d.ts:1
> import { Command } from "../../Interfaces";
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Object.compileFunction (node:vm:352:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
>     at Module._compile (node:internal/modules/cjs/loader:1065:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:94:18)
>     at C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Client\index.js:51:37
>     at Array.forEach (<anonymous>)
>     at ExtendedClient.init (C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Client\index.js:48:39)
>     at Object.<anonymous> (C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\index.js:10:4)       
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by Olian04** [comment]
> > > Still getting the same error.
> > 
> > 
> > Could you post the entire error?
> 
> > C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Commands\Configurations\blacklistWords.d.ts:1
> > import { Command } from "../../Interfaces";
> > ^^^^^^
> > SyntaxError: Cannot use import statement outside a module
> > at Object.compileFunction (node:vm:352:18)
> > at wrapSafe (node:internal/modules/cjs/loader:1031:15)
> > at Module._compile (node:internal/modules/cjs/loader:1065:27)
> > at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> > at Module.load (node:internal/modules/cjs/loader:981:32)
> > at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> > at Module.require (node:internal/modules/cjs/loader:1005:19)
> > at require (node:internal/modules/cjs/helpers:94:18)
> > at C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Client\index.js:51:37
> > at Array.forEach ()
> > at ExtendedClient.init (C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Client\index.js:48:39)
> > at Object. (C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\index.js:10:4)
> > at Module._compile (node:internal/modules/cjs/loader:1101:14)
> > at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
> > at Module.load (node:internal/modules/cjs/loader:981:32)
> > at Function.Module._load (node:internal/modules/cjs/loader:822:12)

`blacklistWords.d.ts` is a typescript definition file. Are you sure you are running my PR? Because it has disabled definition file generation. If you deleted `dist` and are running this PR, then this error can't occur.

**Comment by ProGamer2711** [comment]
Where have you disabled it?

**Comment by Olian04** [comment]
> Where have you disabled it?

by removing `"declaration": true,` in `tsconfig.json`

**Comment by ProGamer2711** [comment]
> > Where have you disabled it?
> 
> by removing `"declaration": true,` in `tsconfig.json`

Turns out I had the declaration thing... Sorry about that. Now I'm getting this error:
`C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Events\blacklistedWords.js.map:1
{"version":3,"file":"blacklistedWords.js","sourceRoot":"","sources":["../../src/Events/blacklistedWords.ts"],"names":[],"mappings":";;;AAEA,gDAA0E;AAE7D,QAAA,KAAK,GAAU;IACxB,IAAI,EAAE,SAAS;IACf,GAAG,EAAE,KAAK,EAAE,MAAM,EAAE,OAAgB,EAAE,EAAE;QACpC,IAAI,CAAC,OAAO,CAAC,KAAK,IAAI,OAAO,CAAC,MAAM,CAAC,EAAE,KAAK,MAAM,CAAC,IAAI,CAAC,EAAE;YAAE,OAAO;QACnE,MAAM,YAAY,GAAG,OAAO,CAAC,OAAO,CAAC,KAAK,CAAC,GAAG,CAAC,CAAC;QAChD,IAAI,QAAQ,GAAY,KAAK,CAAC;QAE9B,MAAM,OAAO,CAAC,GAAG,CACb,YAAY,CAAC,GAAG,CAAC,CAAC,OAAe,EAAE,EAAE;YACjC,IAAI,wCAAU,CAAC,GAAG,CAAC,OAAO,CAAC,KAAK,CAAC,EAAE,CAAC,EAAE,QAAQ,CAAC,OAAO,CAAC,WAAW,EAAE,CAAC;gBAAE,QAAQ,GAAG,IAAI,CAAC;QAC3F,CAAC,CAAC,CACL,CAAC;QAEF,IAAI,QAAQ;YAAE,OAAO,OAAO,CAAC,MAAM,EAAE,CAAC;IAC1C,CAAC;CACJ,CAAA"}
          ^

SyntaxError: Unexpected token ':'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Client\index.js:65:79
    at async C:\Users\Alex\Documents\Programming\NodeJS\Discord bots\Kostegator\dist\Client\index.js:65:31`

**Comment by Olian04** [comment]
Why aren't you just using this PR? It works. You don't need to copy & paste sections of it. Just merge it in and pull down.

**Comment by ProGamer2711** [comment]
Yes, I'm gonna do it now. I just had some uncommitted stuff to sort out.

**Comment by Olian04** [comment]
Why did are you using such a complex `tsconfig` file? Most of the options you had (and still have) enabled are probably not needed, and in this case they result in errors and complications. Don't use configurations if you don't know what they do. The default config for `tsc` is enough in most cases.

**Comment by ProGamer2711** [comment]
What should I do about the `tsconfig.json` file?

**Comment by Olian04** [comment]
> What should I do about the `tsconfig.json` file?

Start removing lines. Remove 1 line, run the code, if it fails, keep that line, if it doesn't fail, remove another line.
That's not how you usually do it, but it will work for you.

**Comment by ProGamer2711** [comment]
Ok, I'll try.

**Comment by Olian04** [comment]
Out of curiosity. Where did you get this `tsconfig` file from? Did you copy it from some other repo? or some tutorial?

**Comment by ProGamer2711** [comment]
A tutorial

**Comment by ProGamer2711** [comment]
`.gitignore` won't let me add `config.json`

**Comment by Olian04** [comment]
Run `git rm src/config.json`. This will delete `config.json` and remove it from being tracked by git. `.gitignore` only limits which files can be ADDED to be tracked by git. If a file is already tracked by git then adding it to `.gitignore`  wont do anything.

**Comment by ProGamer2711** [comment]
Hey, so I did that. Can I add the `config.json` file before the commit or do I have to add it after I commit? I know nothing will change. Also the bot is running but not responding to commands.

**Comment by Olian04** [comment]
Commit first. Then you can create `config.json` again.

**Comment by ProGamer2711** [comment]
Ok I did that.

**Comment by Olian04** [comment]
You have quite a large code base. I have no idea of why your bot doesn't work as expected. That is something you'll have to debug on your own :)

**Comment by ProGamer2711** [comment]
Ok. Still thank you. Another thing. I have a folder `src/Citation/data` which has a font and an image which I need. They aren't going to the `dist` folder. Any idea how to fix that?

**Comment by ProGamer2711** [comment]
Btw I fixed the error. Thank you so much.

**Comment by Olian04** [comment]
@ProGamer2711 those files shouldn't be in your `src` folder to begin with. That folder is only for code. Put your static resources in a separate folder. Like `resources`. In this case `resources/fonts`

**Comment by ProGamer2711** [comment]
Thank you. I did that. You're the best. This solves all of my problems.

**Pull request merged**
